# Auto-generated from RamanBioLib (ODbL-1.0). Diagnostic peaks (rel.I>=0.40).
# Source: Teran et al., Chemom. Intell. Lab. Syst. 264 (2025) 105476.
# Paper: https://www.sciencedirect.com/science/article/pii/S0169743925001613
# Project: https://github.com/mteranm/ramanbiolib
# Used with the authors' permission (M. Teran, Universitat Oberta de Catalunya).
RAMANBIOLIB_BANDS = [
    (452, "RamanBioLib: l-proline"),
    (477, "RamanBioLib: amylopectin, lactose"),
    (481, "RamanBioLib: amylose"),
    (485, "RamanBioLib: glycerol"),
    (495, "RamanBioLib: d-(+)-mannose"),
    (498, "RamanBioLib: chitin"),
    (499, "RamanBioLib: papain"),
    (504, "RamanBioLib: glycine"),
    (513, "RamanBioLib: n-acetyl- d-glucosamine"),
    (515, "RamanBioLib: l-serine"),
    (523, "RamanBioLib: d-(+)-trehalose"),
    (526, "RamanBioLib: d-(+)-xylose"),
    (530, "RamanBioLib: d-(+)-galactosamine, d-(+)-mannose"),
    (540, "RamanBioLib: d-(+)-trehalose"),
    (541, "RamanBioLib: d-(+)-dextrose"),
    (542, "RamanBioLib: β-d-glucose, l-valine"),
    (548, "RamanBioLib: cytosine"),
    (560, "RamanBioLib: l-threonine"),
    (566, "RamanBioLib: ascorbic acid"),
    (578, "RamanBioLib: n-acetyl- d-glucosamine"),
    (611, "RamanBioLib: malic acid, l-serine"),
    (617, "RamanBioLib: thymine"),
    (625, "RamanBioLib: glutathione"),
    (626, "RamanBioLib: d-(-)-fructose"),
    (629, "RamanBioLib: ascorbic acid"),
    (631, "RamanBioLib: acetyl coenzyme a"),
    (640, "RamanBioLib: acetoacetate"),
    (642, "RamanBioLib: l-proline"),
    (643, "RamanBioLib: papain, o-phospho-l-tyrosine"),
    (650, "RamanBioLib: guanine"),
    (660, "RamanBioLib: glutathione"),
    (669, "RamanBioLib: d-(+)-fucose"),
    (679, "RamanBioLib: glutathione"),
    (701, "RamanBioLib: cholesterol"),
    (719, "RamanBioLib: l-α-phosphatidylcholine"),
    (722, "RamanBioLib: coenzyme a"),
    (723, "RamanBioLib: adenine"),
    (724, "RamanBioLib: acetyl coenzyme a"),
    (728, "RamanBioLib: dna"),
    (740, "RamanBioLib: thymine"),
    (749, "RamanBioLib: malic acid, cytochrome c, cytochrome b5, cytochrome p450"),
    (751, "RamanBioLib: hemoglobin, myoglobin"),
    (755, "RamanBioLib: l-tryptophan"),
    (761, "RamanBioLib: lactalbumin"),
    (762, "RamanBioLib: α-chymotrypsinogen a (type ii)"),
    (764, "RamanBioLib: elastase"),
    (765, "RamanBioLib: lactalbumin"),
    (776, "RamanBioLib: l-valine, glutathione"),
    (780, "RamanBioLib: l-threonine"),
    (784, "RamanBioLib: citric acid, dna, rna, o-phospho-l-threonine"),
    (787, "RamanBioLib: phosphoenolpyruvate"),
    (790, "RamanBioLib: uracil, n-acetyl- d-glucosamine"),
    (792, "RamanBioLib: cytosine"),
    (813, "RamanBioLib: l-serine, rna"),
    (815, "RamanBioLib: d-(+)-fucose, o-phospho-l-serine"),
    (818, "RamanBioLib: d-(-)-fructose"),
    (820, "RamanBioLib: ascorbic acid, glycerol"),
    (828, "RamanBioLib: l-tyrosine"),
    (830, "RamanBioLib: acetoacetate, d-(+)-mannose, papain"),
    (834, "RamanBioLib: l-proline, papain, pyruvate"),
    (838, "RamanBioLib: d-(+)-trehalose, ferritin"),
    (841, "RamanBioLib: β-d-glucose, d-(+)-dextrose"),
    (842, "RamanBioLib: l-proline"),
    (843, "RamanBioLib: d-(-)-arabinose"),
    (849, "RamanBioLib: l-valine"),
    (850, "RamanBioLib: glycerol, l-proline"),
    (851, "RamanBioLib: l-alanine"),
    (853, "RamanBioLib: l-serine"),
    (854, "RamanBioLib: amylose"),
    (856, "RamanBioLib: papain, glutathione transferase"),
    (857, "RamanBioLib: l-glutamate, papain"),
    (859, "RamanBioLib: collagen"),
    (861, "RamanBioLib: d-(+)-mannose"),
    (862, "RamanBioLib: collagen"),
    (872, "RamanBioLib: d-(+)-galactosamine, d-(-)-fructose"),
    (874, "RamanBioLib: l-tryptophan, o-phospho-l-threonine, l-threonine"),
    (877, "RamanBioLib: pepsin, l-proline"),
    (879, "RamanBioLib: d-(+)-fucose"),
    (882, "RamanBioLib: d-(+)-mannose"),
    (885, "RamanBioLib: glutathione, collagen"),
    (890, "RamanBioLib: pepsin"),
    (894, "RamanBioLib: glycine"),
    (895, "RamanBioLib: chitin"),
    (899, "RamanBioLib: l-proline"),
    (903, "RamanBioLib: d-(+)-xylose"),
    (912, "RamanBioLib: d-(+)-trehalose"),
    (914, "RamanBioLib: β-d-glucose, o-phospho-l-threonine"),
    (916, "RamanBioLib: l-proline, lactose"),
    (917, "RamanBioLib: glutathione"),
    (924, "RamanBioLib: collagen"),
    (926, "RamanBioLib: papain"),
    (928, "RamanBioLib: acetoacetate"),
    (929, "RamanBioLib: n-acetyl- d-glucosamine"),
    (930, "RamanBioLib: l-proline, o-phospho-l-serine"),
    (931, "RamanBioLib: papain, glutathione"),
    (933, "RamanBioLib: papain"),
    (936, "RamanBioLib: succinic acid, amylose"),
    (940, "RamanBioLib: amylopectin, collagen, o-phospho-l-threonine, l-threonine"),
    (942, "RamanBioLib: l-glutamate, citric acid"),
    (944, "RamanBioLib: amylose"),
    (945, "RamanBioLib: albumin"),
    (948, "RamanBioLib: l-valine"),
    (955, "RamanBioLib: chitin"),
    (964, "RamanBioLib: malic acid"),
    (973, "RamanBioLib: n-acetyl- d-glucosamine, d-fructose-6-phosphate"),
    (982, "RamanBioLib: l-arginine"),
    (994, "RamanBioLib: l-proline"),
    (1003, "RamanBioLib: lectin, ferritin, lactalbumin"),
    (1004, "RamanBioLib: l-phenylalanine, carbonic anhydrase, albumin, pepsin"),
    (1005, "RamanBioLib: α-chymotrypsinogen a (type ii), α-chymotrypsinogen a (type ii)"),
    (1006, "RamanBioLib: carbonic anhydrase, glutathione transferase"),
    (1007, "RamanBioLib: carbonic anhydrase, albumin"),
    (1008, "RamanBioLib: lactalbumin, ferritin, l-serine"),
    (1009, "RamanBioLib: lectin, l-tryptophan, elastase, albumin, lactalbumin"),
    (1010, "RamanBioLib: pepsinogen, glutathione transferase"),
    (1011, "RamanBioLib: lectin, papain, α-chymotrypsinogen a (type ii), papain"),
    (1014, "RamanBioLib: elastase"),
    (1020, "RamanBioLib: n-acetyl- d-glucosamine"),
    (1021, "RamanBioLib: lactose"),
    (1031, "RamanBioLib: lactose"),
    (1034, "RamanBioLib: phosphoenolpyruvate"),
    (1035, "RamanBioLib: l-proline"),
    (1036, "RamanBioLib: elastase, pepsinogen"),
    (1038, "RamanBioLib: lectin"),
    (1042, "RamanBioLib: pepsin"),
    (1045, "RamanBioLib: l-proline, amylose"),
    (1053, "RamanBioLib: lactose"),
    (1054, "RamanBioLib: β-d-glucose"),
    (1055, "RamanBioLib: glycerol"),
    (1059, "RamanBioLib: chitin"),
    (1061, "RamanBioLib: 14-methylpentadecanoic acid, 15-methylpalmiticacid, lauric acid, tristearin, d-(+)-trehalose"),
    (1062, "RamanBioLib: myristic acid, trimyristin, tripalmitin, d-(+)-galactosamine, stearic acid"),
    (1063, "RamanBioLib: myristic acid, palmitic acid, 12-methyltetradecanoic acid, tricaprin, trilaurin"),
    (1066, "RamanBioLib: arachidic acid"),
    (1067, "RamanBioLib: palmitic acid, l-arginine, stearic acid"),
    (1075, "RamanBioLib: β-d-glucose, d-(+)-dextrose"),
    (1080, "RamanBioLib: d-(+)-trehalose"),
    (1081, "RamanBioLib: triolein"),
    (1082, "RamanBioLib: amylopectin"),
    (1083, "RamanBioLib: amylose"),
    (1085, "RamanBioLib: l-α-phosphatidylethanolamine"),
    (1086, "RamanBioLib: d-(+)-xylose"),
    (1087, "RamanBioLib: d-(+)-mannose, lactose, o-phospho-l-serine"),
    (1089, "RamanBioLib: l-α-phosphatidylcholine"),
    (1096, "RamanBioLib: cellulose, l-α-phosphatidylethanolamine, l-α-phosphatidylcholine, dna"),
    (1098, "RamanBioLib: 12-methyltetradecanoic acid, rna"),
    (1102, "RamanBioLib: d-(+)-trehalose"),
    (1106, "RamanBioLib: d-(+)-mannose"),
    (1107, "RamanBioLib: chitin"),
    (1108, "RamanBioLib: d-(+)-dextrose"),
    (1109, "RamanBioLib: amylopectin"),
    (1110, "RamanBioLib: glycerol"),
    (1111, "RamanBioLib: trierucin"),
    (1113, "RamanBioLib: d-(+)-fucose"),
    (1115, "RamanBioLib: d-(+)-xylose"),
    (1120, "RamanBioLib: d-(+)-trehalose, lactose, β-d-glucose, cellulose"),
    (1123, "RamanBioLib: amylose"),
    (1125, "RamanBioLib: myristic acid, tricaprin"),
    (1126, "RamanBioLib: n-acetyl- d-glucosamine"),
    (1127, "RamanBioLib: lauric acid, trilaurin, amylopectin, pepsinogen"),
    (1128, "RamanBioLib: myristic acid, cytochrome c"),
    (1129, "RamanBioLib: palmitic acid, trimyristin, sphingomyelin, d-(+)-fucose"),
    (1130, "RamanBioLib: ascorbic acid, tripalmitin, tristearin, cytochrome b5, cytochrome p450"),
    (1131, "RamanBioLib: hemoglobin, myoglobin, triarachidin, tribehenin, cholesteryl palmitate"),
    (1132, "RamanBioLib: palmitic acid, arachidic acid"),
    (1133, "RamanBioLib: cholesteryl stearate"),
    (1135, "RamanBioLib: 14-methylpentadecanoic acid, 15-methylpalmiticacid"),
    (1141, "RamanBioLib: 12-methyltetradecanoic acid"),
    (1142, "RamanBioLib: lactose"),
    (1143, "RamanBioLib: d-(+)-galactosamine"),
    (1149, "RamanBioLib: d-(+)-trehalose, chitin"),
    (1155, "RamanBioLib: d-(+)-fucose"),
    (1156, "RamanBioLib: β-carotene"),
    (1172, "RamanBioLib: cytochrome c, o-phospho-l-tyrosine"),
    (1178, "RamanBioLib: cholesterol"),
    (1210, "RamanBioLib: o-phospho-l-tyrosine"),
    (1226, "RamanBioLib: riboﬂavin"),
    (1230, "RamanBioLib: o-phospho-l-tyrosine"),
    (1234, "RamanBioLib: guanine"),
    (1235, "RamanBioLib: uracil"),
    (1236, "RamanBioLib: carbonic anhydrase, lectin, elastase, lectin"),
    (1237, "RamanBioLib: carbonic anhydrase"),
    (1239, "RamanBioLib: α-chymotrypsinogen a (type ii)"),
    (1240, "RamanBioLib: elastase, α-chymotrypsinogen a (type ii), α-chymotrypsinogen a (type ii), l-proline, rna"),
    (1241, "RamanBioLib: carbonic anhydrase"),
    (1245, "RamanBioLib: pepsin"),
    (1246, "RamanBioLib: lectin"),
    (1247, "RamanBioLib: pepsinogen"),
    (1248, "RamanBioLib: pepsin"),
    (1249, "RamanBioLib: elastase"),
    (1254, "RamanBioLib: pepsin"),
    (1256, "RamanBioLib: ascorbic acid, d-(+)-fucose"),
    (1257, "RamanBioLib: n-acetyl- d-glucosamine"),
    (1258, "RamanBioLib: papain, lactalbumin, lactalbumin, dna"),
    (1261, "RamanBioLib: lactose"),
    (1262, "RamanBioLib: papain, linoleic acid"),
    (1263, "RamanBioLib: cholesteryl linoleate, α-linolenic acid"),
    (1265, "RamanBioLib: lactalbumin, d-(-)-fructose"),
    (1267, "RamanBioLib: d-(+)-galactosamine, l-proline"),
    (1270, "RamanBioLib: papain"),
    (1271, "RamanBioLib: collagen, l-histidine"),
    (1272, "RamanBioLib: lactalbumin, lactalbumin"),
    (1273, "RamanBioLib: d-(+)-fucose, collagen, collagen"),
    (1275, "RamanBioLib: cytosine"),
    (1278, "RamanBioLib: papain"),
    (1280, "RamanBioLib: glutathione"),
    (1286, "RamanBioLib: glutathione transferase, glutathione transferase"),
    (1293, "RamanBioLib: fumarate"),
    (1294, "RamanBioLib: myristic acid"),
    (1295, "RamanBioLib: sphingomyelin"),
    (1296, "RamanBioLib: palmitic acid, tribehenin, lauric acid, 15-methylpalmiticacid, 14-methylpentadecanoic acid"),
    (1297, "RamanBioLib: trilaurin, triarachidin, trimyristin, tristearin, tripalmitin"),
    (1298, "RamanBioLib: arachidic acid"),
    (1299, "RamanBioLib: tricaprin"),
    (1300, "RamanBioLib: palmitic acid, l-α-phosphatidylethanolamine, stearic acid, l-α-phosphatidylcholine"),
    (1301, "RamanBioLib: triolein, oleic acid"),
    (1302, "RamanBioLib: vaccenic acid, triolein, 12-methyltetradecanoic acid"),
    (1303, "RamanBioLib: tri-11-eicosenoin"),
    (1304, "RamanBioLib: tripalmitolein"),
    (1305, "RamanBioLib: l-alanine, palmitoleic acid, tricaprylin"),
    (1306, "RamanBioLib: oleic acid, tricaproin, cholesteryl linoleate, cholesteryl oleate, acetyl coenzyme a"),
    (1308, "RamanBioLib: myoglobin"),
    (1310, "RamanBioLib: hemoglobin, cytochrome b5, cytochrome p450"),
    (1313, "RamanBioLib: cytochrome c"),
    (1317, "RamanBioLib: l-histidine"),
    (1319, "RamanBioLib: albumin, ascorbic acid"),
    (1321, "RamanBioLib: albumin, n-acetyl- d-glucosamine"),
    (1323, "RamanBioLib: α-chymotrypsinogen a (type ii)"),
    (1325, "RamanBioLib: coenzyme a"),
    (1326, "RamanBioLib: l-serine, lactose"),
    (1328, "RamanBioLib: albumin, chitin"),
    (1330, "RamanBioLib: d-(+)-trehalose, n-acetyl- d-glucosamine"),
    (1331, "RamanBioLib: d-(+)-fucose"),
    (1332, "RamanBioLib: α-chymotrypsinogen a (type ii), adenine"),
    (1333, "RamanBioLib: acetyl coenzyme a"),
    (1334, "RamanBioLib: papain, pepsin, glutathione"),
    (1335, "RamanBioLib: lectin, carbonic anhydrase"),
    (1336, "RamanBioLib: pepsin, cytochrome c"),
    (1339, "RamanBioLib: papain, elastase, amylose, rna"),
    (1340, "RamanBioLib: ferritin, albumin, α-chymotrypsinogen a (type ii), dna"),
    (1341, "RamanBioLib: albumin, l-glutamate"),
    (1342, "RamanBioLib: carbonic anhydrase, glutathione transferase, pepsin, lectin, elastase, l-threonine"),
    (1343, "RamanBioLib: lactalbumin, lactalbumin, glutathione transferase, ferritin, α-chymotrypsinogen a (type ii)"),
    (1344, "RamanBioLib: α-chymotrypsinogen a (type ii)"),
    (1345, "RamanBioLib: riboﬂavin, lectin"),
    (1346, "RamanBioLib: carbonic anhydrase"),
    (1347, "RamanBioLib: elastase, papain"),
    (1351, "RamanBioLib: l-valine"),
    (1355, "RamanBioLib: l-threonine"),
    (1358, "RamanBioLib: d-(+)-trehalose, l-tryptophan"),
    (1359, "RamanBioLib: l-alanine, lactose"),
    (1360, "RamanBioLib: hemoglobin, cytochrome c, cytochrome b5"),
    (1369, "RamanBioLib: thymine"),
    (1370, "RamanBioLib: horseradish peroxidase, cytochrome p450"),
    (1371, "RamanBioLib: chitin, d-(+)-trehalose"),
    (1377, "RamanBioLib: horseradish peroxidase, dna"),
    (1378, "RamanBioLib: l-proline"),
    (1379, "RamanBioLib: amylose"),
    (1380, "RamanBioLib: myoglobin, lactose, n-acetyl- d-glucosamine"),
    (1389, "RamanBioLib: l-proline"),
    (1399, "RamanBioLib: acetoacetate"),
    (1401, "RamanBioLib: l-glutamate"),
    (1407, "RamanBioLib: coenzyme a"),
    (1408, "RamanBioLib: pyruvate, o-phospho-l-serine, o-phospho-l-threonine, l-threonine"),
    (1414, "RamanBioLib: chitin"),
    (1420, "RamanBioLib: succinic acid, coenzyme a"),
    (1421, "RamanBioLib: palmitic acid, l-glutamate"),
    (1422, "RamanBioLib: acetoacetate, myristic acid"),
    (1423, "RamanBioLib: l-tryptophan"),
    (1426, "RamanBioLib: palmitic acid"),
    (1428, "RamanBioLib: cholesteryl stearate"),
    (1430, "RamanBioLib: fumarate"),
    (1433, "RamanBioLib: myristic acid"),
    (1434, "RamanBioLib: l-glutamate"),
    (1436, "RamanBioLib: l-arginine"),
    (1437, "RamanBioLib: sphingomyelin"),
    (1438, "RamanBioLib: trielaidin, palmitic acid, myristic acid, linoleic acid"),
    (1439, "RamanBioLib: vaccenic acid"),
    (1440, "RamanBioLib: triolein, oleic acid, tri-11-eicosenoin, triolein, 12-methyltetradecanoic acid"),
    (1441, "RamanBioLib: trierucin, elaidic acid, stearic acid, cholesteryl oleate, 14-methylhexadecanoic acid"),
    (1442, "RamanBioLib: cholesteryl palmitate, cholesteryl linoleate, cholesterol, l-α-phosphatidylcholine, tricaprylin"),
    (1443, "RamanBioLib: tricaprin, trimyristin, tristearin, palmitic acid"),
    (1444, "RamanBioLib: cholesteryl stearate, oleic acid, tricaproin, tripalmitolein, tripetroselinin"),
    (1445, "RamanBioLib: stearic acid, lactalbumin, papain, 14-methylpentadecanoic acid, lactalbumin"),
    (1446, "RamanBioLib: lauric acid, phosphoenolpyruvate"),
    (1447, "RamanBioLib: 12-methyltetradecanoic acid, 13-methylmyristicacid"),
    (1448, "RamanBioLib: 15-methylpalmiticacid"),
    (1449, "RamanBioLib: ferritin, elastase, pepsin, elastase"),
    (1450, "RamanBioLib: collagen, albumin, carbonic anhydrase, lectin"),
    (1451, "RamanBioLib: α-chymotrypsinogen a (type ii), lectin"),
    (1452, "RamanBioLib: papain, lactalbumin, lectin, α-chymotrypsinogen a (type ii), d-(+)-fucose"),
    (1453, "RamanBioLib: collagen, elastase, carbonic anhydrase, carbonic anhydrase"),
    (1454, "RamanBioLib: glutathione transferase, pepsin, albumin, pepsin, tricaprin"),
    (1455, "RamanBioLib: glutathione transferase"),
    (1456, "RamanBioLib: collagen, ferritin, tripetroselinin"),
    (1457, "RamanBioLib: elastase, pepsinogen"),
    (1459, "RamanBioLib: trilaurin, 12-methyltetradecanoic acid, lauric acid"),
    (1460, "RamanBioLib: α-chymotrypsinogen a (type ii), lectin"),
    (1461, "RamanBioLib: ferritin"),
    (1462, "RamanBioLib: trierucin, l-serine, l-alanine"),
    (1463, "RamanBioLib: trielaidin, stearic acid"),
    (1464, "RamanBioLib: 15-methylpalmiticacid, cholesteryl palmitate, elaidic acid"),
    (1465, "RamanBioLib: glycerol, trimyristin, tristearin, 14-methylpentadecanoic acid, 14-methylhexadecanoic acid"),
    (1466, "RamanBioLib: tribehenin, tripalmitin, stearic acid, arachidic acid"),
    (1467, "RamanBioLib: triarachidin, palmitic acid"),
    (1468, "RamanBioLib: cholesteryl stearate"),
    (1469, "RamanBioLib: 13-methylmyristicacid, o-phospho-l-serine"),
    (1472, "RamanBioLib: 12-methyltetradecanoic acid"),
    (1482, "RamanBioLib: l-alanine, rna"),
    (1489, "RamanBioLib: dna"),
    (1515, "RamanBioLib: β-carotene"),
    (1553, "RamanBioLib: carbonic anhydrase"),
    (1554, "RamanBioLib: α-chymotrypsinogen a (type ii)"),
    (1555, "RamanBioLib: lactalbumin, elastase"),
    (1556, "RamanBioLib: elastase, lactalbumin"),
    (1560, "RamanBioLib: horseradish peroxidase"),
    (1575, "RamanBioLib: horseradish peroxidase, rna"),
    (1578, "RamanBioLib: dna"),
    (1585, "RamanBioLib: myoglobin, hemoglobin, hemoglobin, myoglobin, cytochrome c, cytochrome b5, cytochrome p450"),
    (1610, "RamanBioLib: albumin, o-phospho-l-tyrosine"),
    (1615, "RamanBioLib: ferritin, papain"),
    (1617, "RamanBioLib: papain, pepsin"),
    (1618, "RamanBioLib: papain"),
    (1619, "RamanBioLib: lactalbumin, carbonic anhydrase"),
    (1620, "RamanBioLib: elastase, glutathione transferase, carbonic anhydrase, cytochrome b5, cytochrome p450"),
    (1622, "RamanBioLib: glutathione transferase"),
    (1623, "RamanBioLib: pepsinogen"),
    (1625, "RamanBioLib: elastase"),
    (1630, "RamanBioLib: horseradish peroxidase"),
    (1632, "RamanBioLib: horseradish peroxidase"),
    (1640, "RamanBioLib: myoglobin, trilinolenin, hemoglobin, cytochrome c"),
    (1653, "RamanBioLib: arachidonic acid, ascorbic acid"),
    (1654, "RamanBioLib: α-linolenic acid, linoleic acid, trilinolein"),
    (1655, "RamanBioLib: trilinolenin, palmitoleic acid, vaccenic acid, oleic acid, triolein"),
    (1656, "RamanBioLib: trilinolenin, albumin, tripalmitolein, tri-11-eicosenoin"),
    (1657, "RamanBioLib: albumin, trilinolein, albumin, oleic acid, l-α-phosphatidylethanolamine"),
    (1658, "RamanBioLib: ferritin"),
    (1660, "RamanBioLib: trierucin, rna"),
    (1661, "RamanBioLib: ferritin"),
    (1662, "RamanBioLib: glutathione transferase, cholesteryl linoleate, ferritin"),
    (1664, "RamanBioLib: glutathione transferase"),
    (1665, "RamanBioLib: lactalbumin, carbonic anhydrase, lactalbumin, papain"),
    (1666, "RamanBioLib: collagen"),
    (1667, "RamanBioLib: lectin, ascorbic acid, carbonic anhydrase"),
    (1668, "RamanBioLib: collagen, papain, collagen, α-chymotrypsinogen a (type ii), dna"),
    (1669, "RamanBioLib: α-chymotrypsinogen a (type ii), carbonic anhydrase, elastase, pepsin"),
    (1670, "RamanBioLib: lactalbumin"),
    (1671, "RamanBioLib: thymine, elastase, pepsin"),
    (1672, "RamanBioLib: α-chymotrypsinogen a (type ii), papain, cholesterol, trielaidin"),
    (1675, "RamanBioLib: pepsin"),
    (1676, "RamanBioLib: elastase, lectin, pepsinogen"),
    (1679, "RamanBioLib: lectin"),
    (1700, "RamanBioLib: pyruvate"),
    (1703, "RamanBioLib: acetoacetate"),
    (1715, "RamanBioLib: acetoacetate"),
]
